 "use client"
import s from "./layoutmain.module.css"
import {LayoutLeft} from "./layoutleft"
import { useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { RiCloseLine } from "react-icons/ri";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

interface TanstackProviderProps {
                                      children: React.ReactNode;
                                      userdata: any
                                }

export const LayoutMain = ({ children, userdata }: TanstackProviderProps) => {  

//   let userdata = await isloggedv4_clerk();


const uploadObj = useState(false);
const [left, setleft] = useState(false);

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
             
  return (<html lang="en"><body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> 
  <div style={{backgroundColor:"#db2d2d", padding:12, paddingBottom:20, fontSize:10, color:"white"}}>
    
    Sistemimizde büyük bir güncelleme yapılmaktadır. Tüm servisleri geri getiriyoruz. İlk olarak iş ilanlarıyla ilgili bazı servisler devreye alınmıştır. Diğer servisleri de hızlıca açacağız. Kesintiden ötürü özür dileriz.
  </div>
                                                        
                                                                          <div className={s.shell}> 
                                                                                    {/* {JSON.stringify(props)} */}
                                                                                    <div className={s.left}><LayoutLeft  uploadObj={uploadObj} /></div>  
                                                                                        
                                                                                        {left && <div className={s.left_mobile}  onClick={()=>setleft(false)}>                
                                                                                                    <LayoutLeft uploadObj={uploadObj}  />
                                                                                                    {left && <div className={s.left_mobile_close_button} onClick={()=>setleft(false)}> <RiCloseLine size={30}/> </div>} 
                                                                                        </div>} 
                                                                                        <div style={{width:"100%", padding:20}}> {children} </div>
                                                                          </div>                                                                 
            </body>
            </html>                                                                          
        );
};








